// src/data/products.js

// Lista de productos para autocompletado en el cotizador (solo descripción y unidad)
export const products = [
  { description: "ALAMBRE RECOCIDO", unit: "KG" },
  { description: "ALAMBRON 1/4", unit: "KG" },
  { description: "ALAMBRÓN RECTO CORTE A MEDIDAS", unit: "KG" },
  { description: "ANILLOS EN ALAMBRON", unit: "KG" },
  { description: "ANILLOS ESPECIALES EN VARILLA Y ALAMBRÓN", unit: "KG" },
  { description: "ANILLOS ESPECIALES EN VARILLIN 5/16", unit: "KG" },
  { description: "ARMEX 10X10 ( 15X15 )", unit: "PZ" },
  { description: "ARMEX 10X15 ( 15X20 )", unit: "PZ" },
  { description: "ARMEX 10X20 ( 15X25 )", unit: "PZ" },
  { description: "ARMEX 10X25 ( 15X30 )", unit: "PZ" },
  { description: "ARMEX 12X12 - 4", unit: "PZ" },
  { description: "ARMEX  12 X 20", unit: "PZ" },
  { description: "ARMEX  12 X 30", unit: "PZ" },
  { description: 'CLAVO DE 2" A  4"  ( POR TONELADA)', unit: "KG" },
  { description: 'CLAVO DE 2" A 4"       CAJAS 25 KGS', unit: "KG" },
  {
    description: 'CLAVO DE 2" A  4"   A  GRANEL (CAJAS DE 1 Y  5 KG)',
    unit: "KG",
  },
  { description: 'CLAVO DE 1" A 1 1/2 "   CAJAS 25 KGS', unit: "KG" },
  {
    description: 'CLAVO DE 1" A 1 1/2 "   A GRANEL (CAJAS DE 1 Y 5 KG)',
    unit: "KG",
  },
  { description: 'CLAVO DE CONCRETO 2" A 4"   CAJAS 25 KGS', unit: "KG" },
  {
    description: 'CLAVO DE CONCRETO 2" A 4"   A GRANEL (CAJAS DE 1 Y 5 KG)',
    unit: "KG",
  },
  { description: 'CLAVO DE CONCRETO 1" A 1 1/2"    CAJAS 25 KGS', unit: "KG" },
  {
    description:
      'CLAVO DE CONCRETO 1" A 1 1/2"    A GRANEL (CAJAS DE 1 Y 5 KG)',
    unit: "KG",
  },
  { description: "MALLA ELECTROSOLDADA 66-1010", unit: "PZ" },
  { description: "MALLA ELECTROSOLDADA 66-88", unit: "PZ" },
  { description: "MALLA ELECTROSOLDADA 66-66", unit: "PZ" },
  { description: "MALLA ELECTROSOLDADA 66-44", unit: "PZ" },
  { description: 'VARILLA DE 3/8" Y 1/2" A 12 MTS', unit: "KG" },
  { description: 'VARILLA DE 5/8" A 1 1/2"', unit: "KG" },
  { description: "VARILLIN G-6000 3/16 Y 5/32", unit: "KG" },
  { description: "VARILLIN G-600 5/16 Y  1/4", unit: "KG" },
  { description: "CEMENTO GRIS   ( 20 BTOS X TON ) CRUZ AZUL", unit: "KG" },
  { description: "CEMENTO GRIS   ( 20 BTOS X TON ) MOCTEZUMA", unit: "KG" },
  { description: "CEMENTO BLANCO (BTOS  50 KG - 1 TON 20 BTOS)", unit: "KG" },
  {
    description: "MORTERO  (BTOS  50 KG - 1 TON 20 BTOS) MOCTEZUMA",
    unit: "KG",
  },
  { description: "CAL    (BTOS. 25 KGS.   -  1 TON. 40 BTOS. )", unit: "KG" },
  { description: "PEGAZULEJO CREST (BULTOS 20 KG)", unit: "KG" },
  { description: "TABICON LIGERO (12.5X25.5X7)", unit: "PZ" },
  { description: "TABICON PESADO", unit: "PZ" },
  { description: "BLOCK LIGERO Y PESADO (12X38X18)", unit: "PZ" },
  { description: "TABIQUE ROJO (24 X5X12)", unit: "PZ" },
  { description: "METAL DEPLEGADO", unit: "ROLLO" },
  { description: "YESO (BULTOS 40 KG - 1 TON. = 25 BULTOS )", unit: "PZ" },
  { description: "ESCALERILLA TRAMO 3MT (MURO 8,10,12)", unit: "PZ" },
  { description: "TELA DE GALLINERO 1.50 MTR ALTO", unit: "PZ" },
  { description: "TELA DE GALLINERO 1.75 MTR ALTO", unit: "PZ" },
  {
    description: "ARENA  (CARRO 6M3)VIAJES COMPLETOS O MIXTOS SOLO AREA METRO",
    unit: "M3",
  },
  {
    description: "GRAVA (CARRO 6M3)VIAJES COMPLETOS O MIXTOS SOLO AREA METRO",
    unit: "M3",
  },
  { description: "ARENA X COSTAL", unit: "KG" },
  { description: "GRAVA X COSTAL", unit: "KG" },
  { description: "ARENA X M3 ( 20 COSTALES X M3 )", unit: "KG" },
  { description: "GRAVA X M3 ( 20 COSTALES X M3 )", unit: "" },
];
